# Generated by Django 4.2.7 on 2024-06-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesFlow', '0003_monthsheet_efect_current_monthsheet_efect_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthsheet',
            name='efect_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthsheet',
            name='efect_goal',
            field=models.IntegerField(default=0),
        ),
    ]
