# Generated by Django 4.2.7 on 2024-06-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesFlow', '0004_alter_monthsheet_efect_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthsheet',
            name='td_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthsheet',
            name='td_goal',
            field=models.IntegerField(default=0),
        ),
    ]
